### ISSUE TITLE
前端基础知识之CSS篇

### ISSUE THREAD

**Issue by zptime** [zptime/blog#17]
### 常用css效果
- [CSS Inspiration -- CSS灵感](https://chokcoco.github.io/CSS-Inspiration/#/./init)
- [You-need-to-know-css](https://lhammer.cn/You-need-to-know-css/#/zh-cn/introduce?v=1)
- [CSS Tricks](https://qishaoxuan.github.io/css_tricks/)

### [彻底搞定 vertical-align 垂直居中不起作用疑难杂症](https://juejin.cn/post/6844903561780789255)

- 问题 1：图片底部会出现间隙：由于空白节点的存在，图片后面相当于跟了一个文本节点。而默认情况下，图片的对齐方式是以父级元素的基线对齐，为了保持与基线对齐，图片底部必须留出间隙，大小为上面提到的半倍文本间距[即(line-height - font-size) / 2]。而且 line-height 的值越大，间隙将越大。
- 解决 1：要去除图片底部的间隙，需要将 line-height 和 vetical-align 属性的其中一个给干掉
  （1）将图片设置为 display:block（利用 vertical-align 的生效前提）；
  （2）将 vertical-align 设置为 top，bottom，或者 middle 等值（利用属性值的表现行为）；
  （3）将 line-height 设置为 0（利用 line-height 为 0 时，基线上移）；
  （4）将 font-size 设置为 0 （如果 line-height 的值为相对值，如 1.5）；
  （5）将 img 设置浮动或者绝对定位（如果布局允许的话）

### [BFC(块级格式化上下文)](https://muyiy.cn/question/css/39.html)

描述：具有 BFC 特性的元素可以看作是隔离了的独立容器，容器里面的元素不会在布局上影响到外面的元素，并且 BFC 具有普通容器所没有的一些特性。

触发条件：只要元素满足下面任一条件即可触发 BFC 特性

- body 根元素
- 浮动元素：float 除 none 以外的值
- 绝对定位元素：position (absolute、fixed)
- display 为 inline-block、table-cells、flex
- overflow 除了 visible 以外的值 (hidden、auto、scroll)

特性及应用：

- 同一个 BFC 下外边距会发生折叠。如果想要避免外边距的重叠，可以将其放在不同的 BFC 容器中
- BFC 可以包含浮动的元素（清除浮动）
- BFC 可以阻止元素被浮动元素覆盖。左边的宽度固定，右边的内容自适应

### [div 水平垂直居中](https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/92)

- flex 布局：justify-content: center;align-items: center;
- absolute 绝对定位：position: absolute; top: 50%; left: 50%;
  - transform: translate(-50%, -50%);
  - width: 50px; height: 10px;margin-left: -25px;margin-top: -5px;
  - left: 0;top: 0;right: 0;bottom: 0;margin: auto;
- grid 布局：
  - div.parent{ display:grid; } div.child{ margin:auto; }
  - div.parent {display: grid;} div.child {justify-self: center;align-self: center;}
- table 布局：
  - div.parent {display: table;} div.child {display: table-cell;vertical-align: middle;text-align: center;}

### [分析比较 opacity: 0、visibility: hidden、display: none 优劣和适用场景](https://muyiy.cn/question/css/57.html)

- display: none;
  1. DOM 结构：浏览器不会渲染 display 属性为 none 的元素，不占据空间；
  2. 事件监听：无法进行 DOM 事件监听；不能点击；
  3. 性能：动态改变此属性时会引起`重排`(reflow)，性能较差；
  4. 继承：不会被子元素继承，毕竟子类也不会被渲染；
  5. transition：transition 不支持 display。
- visibility: hidden;
  1. DOM 结构：元素被隐藏，但是会被渲染不会消失，占据空间；
  2. 事件监听：无法进行 DOM 事件监听；不能点击；
  3. 性 能：动态改变此属性时会引起`重绘`(repaint)，性能较高；
  4. 继 承：会被子元素继承，子元素可以通过设置 visibility: visible; 来取消隐藏；
  5. transition：transition 支持 visibility，visibility 会立即显示，隐藏时会延时。
- opacity: 0;
  1. DOM 结构：透明度为 100%，元素隐藏，占据空间；
  2. 事件监听：可以进行 DOM 事件监听；可以点击；
  3. 性 能：提升为合成层，不会触发`重绘`，性能较高；
  4. 继 承：会被子元素继承,且子元素并不能通过 opacity: 1 来取消隐藏；
  5. transition：transition 支持 opacity，opacity 可以延时显示和隐藏。

### [CSS 预编译器比较：Sass, Scss, Less, Stylus](https://juejin.im/post/5c9b17cbf265da60c95b7c3a)

- Sass (Syntactically Awesome Stylesheets)是一种动态样式语言，Sass 语法属于缩排语法，比 css 比多出好些功能(如变量、嵌套、运算,混入(Mixin)、继承、颜色处理，函数等)，更容易阅读。Sass 的缩排语法，对于写惯 css 前端的 web 开发者来说很不直观，也不能将 css 代码加入到 Sass 里面，因此 sass 语法进行了改良，Sass 3 就变成了 Scss(sassy css)。与原来的语法兼容，只是用{}取代了原来的缩进。
- SCSS (sassy css) 是 Sass 3 引入新的语法，其语法完全兼容 CSS3，并且继承了 Sass 的强大功能。也就是说，任何标准的 CSS3 样式表都是具有相同语义的有效的 SCSS 文件。另外，SCSS 还能识别大部分 CSS hacks（一些 CSS 小技巧）和特定于浏览器的语法，例如：古老的 IE filter 语法。由于 SCSS 是 CSS 的扩展，因此，所有在 CSS 中正常工作的代码也能在 SCSS 中正常工作。对于一个 Sass 用户，只需要理解 Sass 扩展部分如何工作的，就能完全理解 SCSS 大部分扩展，例如变量、parent references 和 指令都是一致的；唯一不同的是，SCSS 需要使用分号和花括号，而不是换行和缩进。
- Less 也是一种动态样式语言. 对 CSS 赋予了动态语言的特性，如变量，继承，运算， 函数. Less 既可以在客户端上运行 (支持 IE 6+, Webkit, Firefox)，也可在服务端运行 (借助 Node.js)。
- Stylus：2010 年产生于 node 社区， 主要用来给 Node 项目进行 CSS 预处理支持，人气不如前两者。Stylus 被称为是一种革命性的新语言，提供一个高效、动态、和使用表达方式来生成 CSS，以供浏览器使用。Stylus 同时支持缩进和 CSS 常规样式书写规则。

### [img 元素底部为何有空白](https://www.zhihu.com/question/21558138)

- 首先需要了解 CSS 对于 display: inline 元素的 vertical-align 各个值的含义。vertical-align 的默认值是 baseline，baseline 和 bottom 之间有一定的距离。实际上，inline 的图片下面那一道空白正是 baseline 和 bottom 之间的这段距离。即使只有图片没有文字，只要是 inline 的图片这段空白都会存在。
- 图片底部的空隙实际上涉及行内元素的布局模型，图片默认的垂直对齐方式是基线，而基线的位置是与字体相关的。所以在某些时候，图片底部的空隙可能是 2px，而有时可能是 4px 或更多。不同的 font-size 应该也会影响到这个空隙的大小。
- 要去掉这段空白，最直接的办法是将图片的 vertical-align 设置为其他值。如果在同一行里有文字混排的话，那应该是用 bottom 或是 middle 比较好。
- top 和 bottom 之间的值即为 line-height。假如把 line-height 设置为 0，那么 baseline 与 bottom 之间的距离也变为 0，那道空白也就不见了。
- 如果没有设置 line-height，line-height 的默认值是基于 font-size 的，视渲染引擎有所不同，但一般是乘以一个系数（比如 1.2）。因此，在没有设置 line-height 的情况下把 font-size 设为 0 也可以达到同样的效果。当然，这样做的后果就是不能图文混排了。

### [浏览器 IMG 图片原生懒加载 loading="lazy"](https://www.zhangxinxu.com/wordpress/2019/09/native-img-loading-lazy/)

Chrome 浏览器(76 以上版本 2019 年)的 IMG 图片和 IFRAME 框架会支持原生懒加载特性，使用 loading="lazy"语法。

```js
<img src="./example.jpg" loading="lazy" alt="zhangxinxu">
```

- HTML loading 属性值如下：
  - lazy：图片或框架懒加载，也就是元素资源快要被看到的时候加载。
  - eager：图片或框架无视一切进行加载。
  - auto：默认值。图片或框架基于浏览器自己的策略进行加载。如果 HTMLImageElement 或者 HTMLIFrameElement 元素没有显式地设置 loading 属性或者 loading 属性的值不合法，则都被当作'auto'处理。
- 如何判断当前浏览器是否支持 loading="lazy"
  - var isSupportLoading = 'loading' in document.createElement('img');
  - var isSupportLoading = 'loading' in new Image();
  - var isSupportLoading = 'loading' in HTMLImageElement.prototype;
- 如何获取 loading 属性值

  - 支持原生 loading 懒加载，如 Google76 版以上

  ```js
  var img = document.querySelector("[loading]");
  var attrLoading = img.loading;
  ```

  - 浏览器并不支持原生的 loading 懒加载，则会返回 undefined，例如在 Firefox 浏览器

  ```js
  // loading自定义扩展
  HTMLElement.prototype.loading = function () {};
  img = document.querySelector("[loading]");
  img.loading;
  ```

### [元素 focus 时，页面不滚动不定位的 JS 处理](https://www.zhangxinxu.com/wordpress/2019/09/js-focus-preventscroll/)

```js
// preventScroll是一个可选参数，默认值是false，表示不阻止聚焦滚动。如果preventScroll参数值是true则表示只聚焦不滚动。
var y = window.pageYOffset;
button.focus({
  preventScroll: true,
});
// IE浏览器的处理
if (window.pageYOffset != y) {
  setTimeout(function () {
    document.documentElement.scrollTop = y;
  }, 0);
}
```

### [键盘可访问性](https://www.zhangxinxu.com/wordpress/2017/04/css-focus-js-improve-accessibility-keyboard/)

- 所谓“键盘可访问性”，指的是用户只使用键盘访问网站的能力。键盘访问网站的常用操作包括：
  - Tab 键索引控件元素；
  - Enter 键触发当前处于 focus 状态的点击行为；
  - 上下键上下滚动网页；
  - Space 空白键滚动一屏网页；
  - Home 键返回顶部；
  - End 键滚动到底部；
  - 其中 Tab 键索引和 Enter 键点击是与交互相关的最重要的两个键盘行为。
- 在全局去除元素的 outline，会导致控件元素被 focus 时候 UI 完全没有任何改变，用户根本就无法知道现在到底哪个元素是处于 focus 状态，键盘可访问性几乎就是 0，在我看看是非常不专业的做法。其实只要平时注意 HTML 语义化，例如按钮不要使用`<span>，<div>`等标签，不要重置 outline，基本上键盘可访问性就已经及格了。
- label 标签和表单元素之间的键盘可访问性：对于 `<form>`表单元素，如果里面有 type 为 submit 类型的按钮，则浏览器天然支持单行输入框的回车提交行为。

```css
/* 借助<label>元素实现按钮样式 */
<input
  id="t"
  type="submit"
  > <label
  class="btn"
  for="t"
  > 提交</label
  > [type="submit"] {
  position: absolute;
  clip: rect(0 0 0 0);
}
.btn {
  display: inline-block;
  padding: 2px 12px;
  background-color: #cd0000;
  color: #fff;
  font-size: 14px;
  cursor: pointer;
}

/* 模拟focus状态的outline效果 */
:focus + label.btn {
  outline: 1px dotted Highlight;
  outline: 5px auto -webkit-focus-ring-color;
}
```

- CSS hover 显示隐藏内容的键盘可访问性：使用 display:none 或者 visibility:hidden 隐藏，会导致隐藏的控件元素没法通过键盘让其显示，因为这两种隐藏方式会让元素无法被 focus。解决：通过 opacity 隐藏和显示。

```css
tr .btn {
  opacity: 0;
  filter: alpha(opacity=0);
}
tr:hover .btn,
tr .btn:focus {
  opacity: 1;
  filter: none;
}
```

- CSS hover 显示下拉内容的键盘可访问性
  - CSS 定位增加:focus 显示，JS 定位增加 focus 事件显示；
  - 引入下拉和浮层索引和回车支持 JS；
  - 粘贴.outline 样式，以及简单的 HTML 关联属性设置；

### [a 标签的 target 属性](https://www.zhangxinxu.com/wordpress/2019/10/a-href-target-window-blank-refresh/)

- a 标签的 target 属性值：
  - \_self：默认值。当前浏览器上下文。
  - \_blank：通常是一个新的标签页，但是用户可以配置浏览器，是否在新窗口打开。
  - \_parent：当前浏览器上下文的的父级上下文，如果没有父级，则行为类似\_self。
  - \_top：最顶级的浏览器上下文。如果没有祖先上下文环境，则行为类似\_self.
  - 实际上，target 还有一个隐藏特性，那就是可以指定为具体的 URL 地址或者任意自定义的名称。

功能：点击一个链接，如果这个链接浏览器已经打开过，则刷新已经打开的链接窗口；如果这个链接没有打开过，则使用新窗口打开这个链接页面

实现：设置链接元素和表单元素的 target 属性值为目标 URL 地址值。如：`<a href="blank.html" target="blank.html">空白页</a>`

### [无外链的 CSS 开发策略](https://www.zhangxinxu.com/wordpress/2019/08/css-no-external-link/)

- 无外链的 CSS 开发策略的好处
  - 节约了大量的请求：页面的渲染和呈现速度快了很多，因为页面渲染的瓶颈往往在于 http/https 请求上
  - 迁移与引用更方便：由于没有任何外链，样式布局或者组件可以直接拷过去复用，不用携带一堆静态资源
  - 没有了跨域问题：字体文件是有跨域问题的，走内联则没有
  - 没有合并的成本：用到哪个图标，复制粘贴下就好
- 无外链的 CSS 开发实践
  - 告别 PNG 图形，全部使用矢量图形
  - 优先使用 SVG Sprites 技术，CSS 中不出现小图标
  - 如果项目比较小，使用的图标不多，没必要使用还是有些维护成本的 SVG Sprites 技术。则优先尝试 CSS 绘制图标，[常见纯 CSS 图标的代码分离与整理](https://www.zhangxinxu.com/wordpress/2019/08/pure-css-icon/)
  - CSS 可以驾驭的图标毕竟有限，此时推荐使用[转义格式](https://www.zhangxinxu.com/wordpress/2018/08/css-svg-background-image-base64-encode/)进行 SVG 内联，方便进行颜色设置
  - [常见纯 CSS 图标的代码分离与整理](https://www.zhangxinxu.com/wordpress/2019/08/pure-css-icon/)

### [让 CSS flex 布局最后一行列表左对齐的 N 种方法](https://www.zhangxinxu.com/wordpress/2019/08/css-flex-last-align/)

justify-content 对齐问题描述：在 CSS flex 布局中，justify-content 属性可以控制列表的水平对齐方式，例如 space-between 值可以实现两端对齐。但是，如果最后一行的列表的个数不满，则就会出现最后一行没有完全垂直对齐的问题。

```css
.container {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}
.list {
  width: 24%;
  height: 100px;
  background-color: skyblue;
  margin-top: 15px;
}
```

### [CSS 伪类](https://www.zhangxinxu.com/wordpress/2019/07/css-not-pseudo-class/)

- css 伪类优先级
  - 0 级指没有优先级，1 级是标签选择器，10 级是类选择器，属性选择器，100 级是 ID 选择器
  - 伪类，带有“类”字，其优先级和类选择器一致。但是，其中有个特殊，那就是逻辑伪类的优先级都是 0。例如：:not()，:is()，:where()等。其中:not()伪类的本身没有优先级，最终优先级是由括号里面的选择器决定的。

```js
:not(.disabled) {}    /* 优先级等同于.disabled选择器 */
:not(a) {}    /* 优先级等同于a选择器 */
```

### [scroll 相关 api](https://www.zhangxinxu.com/wordpress/2019/07/js-scrollto-scrollby/)

- 实践代码：

```js
// 1.兼容性很好的scrollLeft和scrollTop
// 设置element左滚动距离100
element.scrollLeft = 100;
// 设置element上滚动距离200
element.scrollTop = 200;

// 2.IE9+浏览器支持，控制窗体滚动距离的pageXOffset和pageYOffset
// 设置窗体左滚动距离100
window.pageXOffset = 100;
// 设置窗体上滚动距离200
window.pageYOffset = 200;

// 3.IE/Edge浏览器不支持的scrollTo和scrollBy：既能作用于windows对象，表示窗体滚动；又可以作用于普通Element元素，表示元素滚动。
// scrollTo()表示滚到到指定的位置，而scrollBy()表示相对当前的位置滚动多少距离
window.scrollTo();
Element.scrollTo();

window.scrollBy();
Element.scrollBy();
```

- 优点
  - 调用统一：scrollLeft/scrollTop 只能作用于元素上，在 window 对象上没有效果。而 pageXOffset/pageYOffset 只能作用于 window 对象上，在元素上没有效果。而 scrollTo 和 scrollBy 不仅可以作用于 window 对象上，还可以作用于元素上。实现的调用的统一。
  - 平滑支持：scrollLeft/scrollTop 和 pageXOffset/pageYOffset 控制滚动定位，想要定位平滑，只能借助于 CSS scroll-behavior 属性，JS 这块设置无力。但是 scrollTo 和 scrollBy 在比较方便，直接有 API 参数支持。
- 缺点
  - 兼容性：scrollTo 和 scrollBy 两个 JS API 在 IE 浏览器中是无效的，如果是需要兼容 IE 浏览器的项目，需要先写个简单的 polyfill

### [CSS filter:hue-rotate 色调旋转滤镜实现按钮批量生产](https://www.zhangxinxu.com/wordpress/2018/11/css-filter-hue-rotate-button/)

- 已知写好了一个蓝色主按钮 CSS，现在要写一个红色按钮样式：

```css
<button class="ui-button ui-button-warning">红按钮</button>

/* 1.传统色值 */
.ui-button-warning,
.ui-button-warning.disabled,
.ui-button-warning.disabled:hover,
.ui-button-warning.loading,
.ui-button-warning.loading:hover {
  border: 1px solid #f4615c;
  background-color: #f4615c;
  color: #fff;
}
.ui-button-warning:hover,
input.ui-button-warning:focus,
button.ui-button-warning:focus {
  background-color: #ff7772;
  border-color: #ff7772;
  color: #fff;
}
.ui-button-warning:not(.disabled):active,
.ui-button-warning:not(.loading):active {
  background-color: #dc5652;
  border-color: #dc5652;
}

/* 2.色调旋转 */
.ui-button-warning {
  filter: hue-rotate(140deg);
}
```

- hue-rotate 滤镜语法：除了支持 deg，还支持其它 CSS3 单位，如圈数 turn 以及弧度 rad 等

```css
hue-rotate(90deg)   /* 90度旋转 */
hue-rotate(.5turn)       /* 180度旋转 */
hue-rotate(3.142rad)     /* 3.142弧度旋转，近似一圈，也就是360度 */
```

- hue-rotate 滤镜与动效：

```css
.bird {
  animation: pulse 5s linear infinite;
}
@keyframes pulse {
  from {
    filter: hue-rotate(0);
  }
  to {
    filter: hue-rotate(360deg);
  }
}
```

### [CSS 创意与视觉表现](https://www.zhangxinxu.com/wordpress/2019/06/cssconf-css-idea/)

```css
/* 平行四边形 */
.shape-left {
  /* 倒三角 */
  shape-outside: polygon(0 0, 100% 0, 0% 100%);
}
.shape-right {
  /* 正三角 */
  shape-outside: polygon(100% 0, 100% 100%, 0 100%);
}

/* 透明方格（深浅交错）背景图 */
.square {
  display: inline-block;
  padding: 300px;
  background-color: #fff;
  background-image: linear-gradient(
      45deg,
      #eee 25%,
      transparent 25%,
      transparent 75%,
      #eee 75%
    ), linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee
        75%);
  background-size: 16px 16px;
  background-position: 0 0, 8px 8px;
}

/* 镂空 */
.clip-shape{
  outline: 9999px solid rgba(0,0,0,.5);  /*方形镂空*/
  box-shadow: 0 0 0 9999px rgba(0,0,0,.75); /*圆角镂空*/
  mask /*五角星镂空*/
}
```

### [纯 CSS 滚动指示器](https://www.zhangxinxu.com/wordpress/2019/06/better-css-scroll-indicator/)

CSS 滚动指示器：滚动指示器指的是页面的顶端会有一个进度条，指示滚动的进度。

```css
/* <div class="indicator"> </div > */
body {
  position: relative;
}
.indicator {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  background: linear-gradient(to right top, teal 50%, transparent 50%) no-repeat;
  background-size: 100% calc(100% - 100vh);
  z-index: 1;
  pointer-events: none;
  mix-blend-mode: darken; /*关键*/
}
.indicator::after {
  content: "";
  position: fixed;
  top: 5px;
  bottom: 0;
  right: 0;
  left: 0;
  background: #fff;
  z-index: 1;
}
```

### [CSS scroll-snap 滚动事件停止及元素位置检测](https://www.zhangxinxu.com/wordpress/2019/04/css-scroll-snap-event-element-detect/)

CSS Scroll Snap：可以让网页容器滚动停止的时候，无需任何 JS 代码的参与，浏览器可以自动平滑定位到指定元素的指定位置。兼容性非常好，移动端几乎可以放心使用。

### [如何 disabled 禁用所有表单 input 输入框元素](https://www.zhangxinxu.com/wordpress/2019/04/disabled-all-form-elements/)

```css
/* 设置pointer-events:none */
form {
  pointer-events: none;
}

/* 使用::before伪元素创建一个浮层该在所有的表单元素上，例如： */
form {
  position: relative;
}
form::before {
  content: '';
  position: absolute;
  left: 0; right: 0; top: 0; bottom: 0;
  background-color: rgba(0,0,0,.001);
}

/* 以上两个方向虽然可以让点击无效，但是并没有阻止键盘访问，也就是Tab键索引，或者回车都能触发表单行为 */
/* 要真正意义上禁用所有的表单元素很简单，嵌套在<fieldset>元素中，然后设置<fieldset>元素disabled就可以了 */
<form>
  <fieldset disabled>
    <legend>表单标题</legend>
    <...>
  </fieldset>
</form>
```

### CSS3 的 box-sizing，怪异盒模型

- box-sizing ： content-box || border-box || inherit;
  - 当设置为 box-sizing:content-box 时，将采用标准模式解析计算，也是默认模式
  - 当设置为 box-sizing:border-box 时，将采用怪异模式解析计算
- 大多数浏览器采用 W3C 标准模型，而 IE 中则采用 Microsoft 自己的标准。怪异模式是“部分浏览器在支持 W3C 标准的同时还保留了原来的解析模式”，怪异模式主要表现在 IE 内核的浏览器。当不对 doctype 进行定义时，会触发怪异模式。
  - 在标准模式下，一个块的总宽度= width + margin(左右) + padding(左右) + border(左右)
  - 在怪异模式下，一个块的总宽度= width + margin(左右)（即 width 已经包含了 padding 和 border 值）

### 弹性 flex 布局

- flex（ flexible box：弹性布局盒模型）,是 2009 年 w3c 提出的一种可以简洁、快速弹性布局的属性。主要思想是给予容器控制内部元素高度和宽度的能力。其中在 webkit 内核的浏览器中使用时，必须加上-webkit-前缀。
- 需注意使用 flex 容器内元素，即 flex item 的 float，clear、vertical-align 属性将失效。

```css
div {
  display: flex; // flex布局
  justify-content: center; // 使子项目水平居中
  align-items: center; // 使子项目垂直居中
}

.box {
  -moz-border-radius: 15px; /* Firefox */
  -webkit-border-radius: 15px; /* Safari 和 Chrome */
  border-radius: 15px; /* Opera 10.5+, 以及使用了IE-CSS3的IE浏览器 */

  -moz-box-shadow: 10px 10px 20px #000; /* Firefox */
  -webkit-box-shadow: 10px 10px 20px #000; /* Safari 和 Chrome */
  box-shadow: 10px 10px 20px #000; /* Opera 10.5+, 以及使用了IE-CSS3的IE浏览器 */

  behavior: url(ie-css3.htc); /* 通知IE浏览器调用脚本作用于'box'类 */
}
```

**Comment by zptime** [comment]
## 1. 水平垂直居中

### 绝对定位水平垂直居中[absolute + margin:auto]

兼容性：IE7 及之前版本不支持

```css
div {
  width: 200px;
  height: 200px;
  background: green;
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  margin: auto;
}
```

### 绝对定位水平垂直居中[absolute + margin 负间距]

```css
div {
  width: 200px;
  height: 200px;
  background: green;
  position: absolute;
  left: 50%;
  top: 50%;
  margin-left: -100px;
  margin-top: -100px;
}
```

### 绝对定位水平垂直居中[absolute + transform]

兼容性：IE8 不支持

```css
div {
  width: 200px;
  height: 200px;
  background: green;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}
```

### 弹性盒模型[不定宽高水平垂直居中]

```css
.box {
  height: 600px; // 去掉高度，只能垂直居中
  display: flex;
  justify-content: center;
  align-items: center;
}
.box > div {
  background: green;
  width: 200px;
  height: 200px;
}
```

### table 布局

将父盒子设置为 `table-cell` 元素，可以使用 `text-align:center` 和 `vertical-align:middle` 实现水平、垂直居中。

比较完美的解决方案是利用三层结构模拟父子结构

```html
<p class="outerBox tableCell"></p>
<p class="ok"></p>
<p class="innerBox">tableCell</p>
<p></p>
<p></p>

<style>
  /*table-cell实现居中，将父盒子设置为table-cell元素，设置text-align:center,vertical-align:
middle;子盒子设置为inline-block元素*/
  .tableCell {
    display: table;
  }
  .tableCell .ok {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
  }
  .tableCell .innerBox {
    display: inline-block;
  }
</style>
```

### calc

对子盒子实现绝对定位，利用 calc 计算位置

```html
<p class="outerBox calc"></p>
<p class="innerBox">calc</p>
<p></p>

<style>
  /_绝对定位，clac 计算位置_/ .calc {
    position: relative;
  }
  .calc .innerBox {
    position: absolute;
    left: -webkit-calc((500px - 200px)/2);
    top: -webkit-calc((120px - 50px)/2);
    left: -moz-calc((500px - 200px)/2);
    top: -moz-calc((120px - 50px)/2);
    left: calc((500px - 200px) / 2);
    top: calc((120px - 50px) / 2);
  }
  #div1 {
    position: absolute;
    left: 50px;
    width: calc(100% - 100px);
    border: 1px solid black;
    background-color: yellow;
    padding: 5px;
    text-align: center;
  }
</style>
```

### 其他方式

- 行内元素水平居中 text-align:center;
- 块元素水平居中 margin:0 auto;
- 单行文字垂直居中 height:n px; line-height:n px;
- 文字相对图片、输入框垂直居中 vertical-align:middle;
- 单行文本垂直居中 text-align + line-height 实现单行文本水平垂直居中
- 垂直居中 #box{width: 200px;height: 200px;background:red;position:absolute;top:50%;margin-top: -100px;}

**Comment by zptime** [comment]
## 2. 圣杯布局（两边固定，中间自适应）

### float 浮动布局

```html
<article class="main">
  <div class="left">左</div>
  <div class="right">右</div>
  <div class="center">
    中
    <h2>浮动布局</h2>
  </div>
</article>

.left{float: left; width: 300px; height: 100px; background: #631D9F;}
.right{float: right; width: 300px; height: 100px; background: red;}
.center{margin-left: 300px; margin-right: 300px; background-color: #4990E2;}
.main::after{ content:''; display: block; clear: both; // 清除浮动}
```

### position 定位布局

```html
<article class="main">
  <div class="left">左</div>
  <div class="center">
    中
    <h2>绝对定位</h2>
  </div>
  <div class="right">右</div>
</article>

.left{position: absolute; left: 0; width: 300px; background-color: red;}
.center{position: absolute; left: 300px; right: 300px; background-color: blue;}
.right{position: absolute; right: 0; width: 300px; background-color: #3A2CAC;}
```

### position 属性有 5 种

- inherit: 继承父元素的 position 属性值
- static: 默认值，没有定位
- fixed: 生成绝对定位的元素,相对于浏览器窗口进行定位（不管屏幕内容怎么滑动,其位置不会改变）
- relative:生成相对定位,相对于其正常位置进行定位
- absolute:生成绝对定位的元素,相当于 static 定位以外的第一个父元素进行定位。

### table 布局

```css
.main {
  width: 100%;
  display: table;
}
.left,
.center,
.right {
  display: table-cell;
}
.left {
  width: 300px;
  background-color: red;
}
.center {
  background-color: blue;
}
.right {
  width: 300px;
  background-color: red;
}
```

### 弹性(flex)布局

```css
.main {
  display: flex;
}
.left {
  width: 400px;
  background-color: red;
}
.center {
  background-color: blue;
  word-break: break-word;
}
.right {
  background-color: red;
  width: 400px;
}
```

### 网格(gird)布局

```css
.div {
  width: 100%;
  display: grid;
  grid-template-rows: 100px;
  grid-template-columns: 300px auto 300px;
}
```

### 总结

以上 5 种实现三栏布局的方式的优缺点：

- 1、float 布局是现在用的比较多的布局，注意要清除浮动
- 2、position 布局只是根据定位属性去直接设置元素位置，个人感觉不太适合用做页面布局
- 3、table 布局使用起来方便，兼容性也不存在问题，但不利于搜索引擎抓取信息
- 4、flex 布局比较强大，但是还是存在 IE 上兼容性问题，只能支持到 IE9 以上
- 5、grid 布局很强大，但是兼容性很差
